version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sync_files/private:/usr/src/app/sync_files/private
    networks:
      - synchrontainer-net
    depends_on:
      - py1
      - py2
      - py3

  py1:
    image: python:3
    networks:
      - synchrontainer-net
    command: sh -c "mkdir -p /usr/src/app/sync_files/public && mkdir -p /usr/src/app/sync_files/private && tail -f /dev/null"

    #command: tail -f /dev/null

  py2:
    image: python:3
    networks:
      - synchrontainer-net
    command: sh -c "mkdir -p /usr/src/app/sync_files/public && mkdir -p /usr/src/app/sync_files/private && tail -f /dev/null"

    #command: tail -f /dev/null

  py3:
    image: python:3
    networks:
      - synchrontainer-net
    command: sh -c "mkdir -p /usr/src/app/sync_files/public && mkdir -p /usr/src/app/sync_files/private && tail -f /dev/null"

    #command: tail -f /dev/null

networks:
  synchrontainer-net:
    driver: bridge
